"""Stubs for `nautilus_trader.core.nautilus_pyo3` (NautilusTrader 1.231).

Modulo Rust exposto via pyo3: ~860 nomes em runtime. Este stub declara apenas os
nomes que outros stubs do pacote importam; todos verificados presentes na 1.231.
Tipos opacos de proposito — a API detalhada vive no codigo Rust.
"""

NANOSECONDS_IN_MILLISECOND: int

class AccountBalance: ...
class BetSide: ...
class FundingRateUpdate: ...
class GreeksConvention: ...
class MessageBus: ...
class OptionSeriesId: ...
class OwnOrderBook: ...
class StrikeRange: ...
